### ISSUE TITLE
Why use render functions

### ISSUE THREAD

**Issue by danieljfarrell** [lpj145/vue-sbtwo#2]
Total noob here. Why are you using render functions https://vuejs.org/v2/guide/render-function.html rather than templates in much of the components?

**Comment by lpj145** [comment]
make a UI template is more than about ui unlike you think, the best part of frameworks ui implement render with functional components because this improve performance, and give more chances top improve and extend component.

**Comment by danieljfarrell** [comment]
OK thanks! So you build up the site with vue components as you have done here https://github.com/lpj145/vue-sbtwo/blob/developer/src/components/VApp.js

I'm learning web things at the moment. Vue seems nice. I'm coming from a backend/desktop background so everything is very new.

**Comment by lpj145** [comment]
is a simple concept, at this moment i'm working with vuetify, in some months vue go to v3, and some things change, the time of i create this repo to now give a great difference for my skills with js and frontend farmeworks.
